export type User = {
  contributors_enabled: boolean;
  created_at: string | null;
  default_profile: boolean;
  default_profile_image: boolean;
  description: string | null;
  entities: object;
  favourites_count: number;
  follow_request_sent: boolean;
  followers_count: number;
  following: boolean;
  friends_count: number;
  geo_enabled: boolean;
  has_extended_profile: boolean;
  id: number;
  id_str: string;
  is_translation_enabled: boolean;
  is_translator: boolean;
  lang: string | null;
  listed_count: number | null;
  location: string | null;
  name: string;
  needs_phone_verification: boolean;
  notifications: boolean;
  profile_background_color: string | null;
  profile_background_image_url: string | null;
  profile_background_image_url_https: string | null;
  profile_background_tile: boolean;
  profile_banner_url: string | null;
  profile_image_url: string | null;
  profile_image_url_https: string | null;
  profile_link_color: string | null;
  profile_location: string | null;
  profile_sidebar_border_color: string | null;
  profile_sidebar_fill_color: string | null;
  profile_text_color: string | null;
  profile_use_background_image: boolean;
  protected: boolean;
  screen_name: string | null;
  status: object;
  statuses_count: number;
  suspended: boolean;
  time_zone: string | null;
  translator_type: string;
  url: string | null;
  utc_offset: string | null;
  verified: boolean;
};
