name: CD (staging:hosting)
on:
  push:
    branches:
      - feature/hosting

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install
        run: yarn install

      - name: Build
        run: yarn predeploy
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

      - name: Deploy to staging only hosting
        uses: w9jds/firebase-action@master
        if: success()
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}
        with:
          args: deploy --only hosting

      - name: Slack notification
        uses: 8398a7/action-slack@v2
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
